# Generated by Django 4.2.7 on 2026-01-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userlogin_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(max_length=10, verbose_name="Mobile Number"),
                ),
                ("gender", models.CharField(max_length=10, verbose_name="Gender")),
                ("experience", models.IntegerField(verbose_name="Years of Experience")),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Specialization"),
                ),
                (
                    "joining_period",
                    models.CharField(max_length=50, verbose_name="Joining Period"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to="users.userlogin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainer",
                "verbose_name_plural": "Trainers",
                "db_table": "trainer",
                "ordering": ["-created_at"],
            },
        ),
    ]
