# Generated by Django 4.2.7 on 2026-01-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_foodentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Subscription End Date"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Subscription Start Date"
            ),
        ),
    ]
