# Generated by Django 4.2.7 on 2026-01-27 05:37

from django.db import migrations
from datetime import timedelta
from django.utils import timezone


def populate_subscription_dates(apps, schema_editor):
    """Populate subscription dates for existing paid users"""
    UserProfile = apps.get_model('users', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        if profile.payment_status and not profile.subscription_end_date:
            # Set subscription start to when they were created or updated
            profile.subscription_start_date = profile.updated_at
            # Add target_months (using 30 days per month)
            profile.subscription_end_date = profile.updated_at + timedelta(days=profile.target_months * 30)
            profile.save()


def reverse_populate(apps, schema_editor):
    """Reverse: clear subscription dates"""
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.all().update(subscription_start_date=None, subscription_end_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_userprofile_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_subscription_dates, reverse_populate),
    ]
