# Generated by Django 4.2.7 on 2026-01-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_userprofile_payment_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="SubscriptionRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("months", models.IntegerField(verbose_name="Renewal Months")),
                ("amount", models.IntegerField(verbose_name="Renewal Amount")),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "renewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Renewed At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_renewals",
                        to="users.userlogin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Renewal",
                "verbose_name_plural": "Subscription Renewals",
                "db_table": "subscription_renewal",
                "ordering": ["-renewed_at"],
            },
        ),
    ]
