# Generated by Django 4.2.7 on 2026-01-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Recipe Name")),
                (
                    "ingredients",
                    models.TextField(
                        verbose_name="Ingredients (comma-separated or newline-separated)"
                    ),
                ),
                ("instructions", models.TextField(verbose_name="Instructions")),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Food Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recipes",
                        to="users.userlogin",
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Recipe",
                "verbose_name_plural": "Food Recipes",
                "db_table": "food_recipe",
                "ordering": ["-created_at"],
            },
        ),
    ]
